_prefs: 
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 2.3429
  - 48.854
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: Trottoirs de Paris
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,trottoirs.00596ac8"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - trottoirs.mss
template: ''
